### ISSUE TITLE
Please provide COPY-MAC as well

### ISSUE THREAD

**Issue by phmarek** [sharplispers/ironclad#42]
So that the parts of a HMAC that get initialized by a salt can be safely updated with only the specific input data.

```lisp
(defparameter *mac* (make-hmac KEY 'sha256))

(defun foo (input)
  (let ((mac (COPY-MAC *mac*)))
    (UPDATE-HMAC mac input)
    (PRODUCE-MAC mac)))
```

Thanks a lot!

**Comment by glv2** [comment]
I think providing a global *copy-mac* method would be a bad idea, because there are MACs for which nonce reuse is a big problem.

For example, using the same key/nonce to authenticate several messages with Poly1305 or GMAC can allow attackers to forge authentication tags for messages created by themselves. It is not as critical for HMAC (as in your example), but it could still 
facilitate replay attacks, which could be a problem depending on the kind of cryptographic protocol used.
